// LUMA V1 — Turkish Strings (User-Facing)
// All user-facing strings in Turkish as per project language rules.

export const TR = {
  common: {
    appName: 'LUMA',
    loading: 'Yükleniyor...',
    save: 'Kaydet',
    cancel: 'İptal',
    confirm: 'Onayla',
    delete: 'Sil',
    edit: 'Düzenle',
    done: 'Tamam',
    next: 'İleri',
    back: 'Geri',
    close: 'Kapat',
    search: 'Ara',
    retry: 'Tekrar Dene',
    yes: 'Evet',
    no: 'Hayır',
    ok: 'Tamam',
    send: 'Gönder',
    share: 'Paylaş',
    apply: 'Uygula',
    reset: 'Sıfırla',
    seeAll: 'Tümünü Gör',
    noResults: 'Sonuç bulunamadı',
    optional: 'İsteğe bağlı',
    required: 'Zorunlu',
    online: 'Çevrimiçi',
    offline: 'Çevrimdışı',
    today: 'Bugün',
    yesterday: 'Dün',
    justNow: 'Az önce',
    minutesAgo: '{count} dakika önce',
    hoursAgo: '{count} saat önce',
    daysAgo: '{count} gün önce',
  },

  auth: {
    welcome: 'LUMA\'ya Hoş Geldin',
    welcomeSubtitle: 'Gerçek bağlantılar burada başlar',
    phoneNumber: 'Telefon Numarası',
    phoneNumberPlaceholder: '+90 5XX XXX XX XX',
    sendCode: 'Kod Gönder',
    verifyCode: 'Kodu Doğrula',
    enterCode: 'Doğrulama kodunu girin',
    codeSent: 'Kod gönderildi',
    codeExpiry: 'Kod {seconds} saniye içinde geçersiz olacak',
    resendCode: 'Kodu Tekrar Gönder',
    selfieVerification: 'Selfie Doğrulama',
    selfieInstructions: 'Yüzünüzü çerçevenin içine yerleştirin ve fotoğraf çekin',
    takeSelfie: 'Selfie Çek',
    retakeSelfie: 'Tekrar Çek',
    verifying: 'Doğrulanıyor...',
    verificationSuccess: 'Doğrulama başarılı!',
    verificationFailed: 'Doğrulama başarısız. Lütfen tekrar deneyin.',
    logout: 'Çıkış Yap',
    logoutConfirm: 'Çıkış yapmak istediğinize emin misiniz?',
    deleteAccount: 'Hesabı Sil',
    deleteAccountConfirm: 'Hesabınız kalıcı olarak silinecektir. Bu işlem geri alınamaz.',
    termsOfService: 'Kullanım Koşulları',
    privacyPolicy: 'Gizlilik Politikası',
    agreeTerms: 'Devam ederek Kullanım Koşullarını ve Gizlilik Politikasını kabul ediyorsunuz',
  },

  onboarding: {
    title: 'Profilini Oluştur',
    stepName: 'İsim',
    stepBirthDate: 'Doğum Tarihi',
    stepGender: 'Cinsiyet',
    stepPhotos: 'Fotoğraflar',
    stepBio: 'Hakkında',
    stepIntention: 'Niyet',
    stepQuestions: 'Sorular',
    firstName: 'Adınız',
    firstNamePlaceholder: 'Adınızı girin',
    birthDate: 'Doğum Tarihi',
    birthDatePlaceholder: 'GG / AA / YYYY',
    gender: 'Cinsiyet',
    genderMale: 'Erkek',
    genderFemale: 'Kadın',
    genderOther: 'Diğer',
    photos: 'Fotoğraflar',
    photosSubtitle: 'En az 2, en fazla 6 fotoğraf ekleyin',
    addPhoto: 'Fotoğraf Ekle',
    bio: 'Hakkında',
    bioPlaceholder: 'Kendinizden bahsedin... (en az 10 karakter)',
    bioCharCount: '{count}/500',
    intention: 'Ne Arıyorsunuz?',
    intentionSerious: 'Ciddi İlişki',
    intentionExploring: 'Keşfediyorum',
    intentionNotSure: 'Emin Değilim',
    questionsTitle: 'Uyumluluk Soruları',
    questionsSubtitle: '20 temel soruyu yanıtlayarak eşleşme puanınızı artırın',
    questionProgress: 'Soru {current}/{total}',
    completeProfile: 'Profili Tamamla',
    profileComplete: 'Profil oluşturuldu!',
    letsStart: 'Keşfetmeye Başla',
  },

  discovery: {
    title: 'Keşfet',
    noMoreProfiles: 'Şu an için gösterecek profil kalmadı',
    checkBackLater: 'Daha sonra tekrar kontrol edin',
    like: 'Beğen',
    pass: 'Geç',
    superLike: 'Süper Beğeni',
    undoSwipe: 'Geri Al',
    dailyLimitReached: 'Günlük beğeni limitine ulaştınız',
    upgradeForMore: 'Daha fazla beğeni için paketinizi yükseltin',
    filters: 'Filtreler',
    filterAge: 'Yaş Aralığı',
    filterDistance: 'Mesafe',
    filterGender: 'Cinsiyet Tercihi',
    filterIntention: 'Niyet Etiketi',
    filterGenderAll: 'Herkesi Göster',
    filterGenderMale: 'Erkek',
    filterGenderFemale: 'Kadın',
    distance: '{km} km',
    age: '{age} yaşında',
    compatibilityScore: '%{score} Uyumlu',
  },

  matches: {
    title: 'Eşleşmeler',
    noMatches: 'Henüz eşleşmeniz yok',
    noMatchesSubtitle: 'Keşfet sayfasından beğenmeye başlayın',
    newMatch: 'Yeni Eşleşme!',
    newMatchSubtitle: '{name} ile eşleştiniz!',
    sendMessage: 'Mesaj Gönder',
    startHarmony: 'Harmony Başlat',
    matchDate: '{date} tarihinde eşleşildi',
    normalMatch: 'Eşleşme',
    superMatch: 'Süper Uyum!',
    superMatchSubtitle: '%{score} üstü uyumluluk!',
    unmatch: 'Eşleşmeyi Kaldır',
    unmatchConfirm: '{name} ile eşleşmeniz kalıcı olarak kaldırılacak. Emin misiniz?',
  },

  harmony: {
    title: 'Harmony',
    noSessions: 'Aktif Harmony oturumu yok',
    noSessionsSubtitle: 'Bir eşleşmenizle Harmony başlatın',
    createSession: 'Oturum Oluştur',
    joinSession: 'Oturuma Katıl',
    sessionActive: 'Oturum aktif',
    sessionEnded: 'Oturum sona erdi',
    sessionCancelled: 'Oturum iptal edildi',
    timeRemaining: '{minutes} dk {seconds} sn kaldı',
    extendSession: 'Süreyi Uzat',
    extendCost: '{gold} Gold ile 15 dakika uzat',
    extendSuccess: 'Oturum 15 dakika uzatıldı!',
    leaveSession: 'Oturumdan Ayrıl',
    leaveConfirm: 'Oturumdan ayrılmak istediğinize emin misiniz?',
    questionCards: 'Soru Kartları',
    gameCards: 'Oyun Kartları',
    revealCard: 'Kartı Aç',
    typing: '{name} yazıyor...',
    voiceCall: 'Sesli Arama',
    videoCall: 'Görüntülü Arama',
    waiting: '{name} bekleniyor...',
    sessionExpiring: 'Oturum bitiyor!',
    sessionExpiringSoon: 'Oturum {minutes} dakika içinde sona erecek',
  },

  chat: {
    title: 'Mesajlar',
    noConversations: 'Henüz mesajınız yok',
    noConversationsSubtitle: 'Eşleşmelerinize mesaj göndererek sohbet başlatın',
    typeMessage: 'Mesaj yazın...',
    sendPhoto: 'Fotoğraf Gönder',
    messageRead: 'Okundu',
    messageDelivered: 'İletildi',
    messageSent: 'Gönderildi',
    typing: 'yazıyor...',
    online: 'Çevrimiçi',
    lastSeen: 'Son görülme: {time}',
    deletedMessage: 'Bu mesaj silindi',
    systemMessage: 'Sistem Mesajı',
    imageMessage: 'Fotoğraf',
    unreadMessages: '{count} okunmamış mesaj',
  },

  profile: {
    title: 'Profil',
    editProfile: 'Profili Düzenle',
    viewProfile: 'Profili Görüntüle',
    myPhotos: 'Fotoğraflarım',
    myBio: 'Hakkımda',
    myIntention: 'Niyetim',
    myBadges: 'Rozetlerim',
    myAnswers: 'Yanıtlarım',
    compatibility: 'Uyumluluk',
    verificationStatus: 'Doğrulama Durumu',
    verified: 'Doğrulanmış',
    notVerified: 'Doğrulanmamış',
    completeVerification: 'Doğrulamayı Tamamla',
    goldBalance: 'Gold Bakiyesi',
    currentPackage: 'Mevcut Paket',
    memberSince: '{date} tarihinden beri üye',
    editBio: 'Hakkımda Düzenle',
    editPhotos: 'Fotoğrafları Düzenle',
    changeIntention: 'Niyeti Değiştir',
    profileViews: 'Profil Görüntülenme',
    swipeStats: 'Beğeni İstatistikleri',
  },

  settings: {
    title: 'Ayarlar',
    account: 'Hesap',
    notifications: 'Bildirimler',
    privacy: 'Gizlilik',
    language: 'Dil',
    darkMode: 'Karanlık Mod',
    about: 'Hakkında',
    help: 'Yardım',
    support: 'Destek',
    rateApp: 'Uygulamayı Değerlendir',
    version: 'Versiyon {version}',
    notificationMatches: 'Eşleşme Bildirimleri',
    notificationMessages: 'Mesaj Bildirimleri',
    notificationHarmony: 'Harmony Bildirimleri',
    notificationBadges: 'Rozet Bildirimleri',
    notificationSystem: 'Sistem Bildirimleri',
    privacyShowOnline: 'Çevrimiçi Durumunu Göster',
    privacyShowDistance: 'Mesafeyi Göster',
    privacyShowLastSeen: 'Son Görülmeyi Göster',
    blockedUsers: 'Engellenen Kullanıcılar',
    deleteAccount: 'Hesabı Sil',
  },

  badges: {
    title: 'Rozetler',
    myBadges: 'Rozetlerim',
    allBadges: 'Tüm Rozetler',
    earned: 'Kazanıldı',
    locked: 'Kilitli',
    earnedDate: '{date} tarihinde kazanıldı',
    firstSpark: 'İlk Kıvılcım',
    firstSparkDesc: 'İlk eşleşmenizi yapın',
    chatMaster: 'Sohbet Ustası',
    chatMasterDesc: '100 mesaj gönderin',
    questionExplorer: 'Merak Uzmanı',
    questionExplorerDesc: 'Tüm uyumluluk sorularını yanıtlayın',
    soulMate: 'Ruh İkizi',
    soulMateDesc: '%90 üstü uyumluluk elde edin',
    verifiedStar: 'Doğrulanmış Yıldız',
    verifiedStarDesc: 'Selfie doğrulamasını tamamlayın',
    coupleGoal: 'Çift Hedefi',
    coupleGoalDesc: 'Bir ilişkiyi aktive edin',
    explorer: 'Kaşif',
    explorerDesc: '50 profil keşfedin',
    goldMember: 'Altın Üye',
    goldMemberDesc: 'Gold veya üstü pakete sahip olun',
    newBadge: 'Yeni Rozet Kazandınız!',
    goldReward: '+{amount} Gold ödül!',
  },

  packages: {
    title: 'Paketler',
    currentPlan: 'Mevcut Plan',
    free: 'Ücretsiz',
    freeDesc: 'Temel özelliklerle başlayın',
    gold: 'Gold',
    goldDesc: 'Premium sorulara erişim ve daha fazla beğeni',
    pro: 'Pro',
    proDesc: 'Tüm özelliklere tam erişim',
    reserved: 'Reserved',
    reservedDesc: 'En özel deneyim',
    subscribe: 'Abone Ol',
    upgrade: 'Yükselt',
    downgrade: 'Düşür',
    cancelSubscription: 'Aboneliği İptal Et',
    cancelConfirm: 'Aboneliğiniz dönem sonuna kadar aktif kalacaktır. İptal etmek istediğinize emin misiniz?',
    monthlyPrice: '₺{price}/ay',
    yearlyPrice: '₺{price}/yıl',
    yearlyDiscount: '%{percent} indirim',
    features: 'Özellikler',
    dailySwipes: 'Günlük {count} beğeni',
    unlimitedSwipes: 'Sınırsız beğeni',
    monthlyGold: 'Aylık {count} Gold',
    premiumQuestions: 'Premium uyumluluk soruları',
    seeWhoLikedYou: 'Sizi beğenenleri görün',
    readReceipts: 'Okundu bilgisi',
    profileBoost: 'Profil öne çıkarma',
    undoSwipe: 'Beğeniyi geri alma',
    priorityInFeed: 'Keşfette öncelik',
    goldTitle: 'Gold',
    goldBalance: 'Bakiye: {amount} Gold',
    buyGold: 'Gold Satın Al',
    goldPack: '{amount} Gold',
    goldPackPrice: '₺{price}',
    goldPackBonus: '+{bonus} bonus!',
    transactionHistory: 'İşlem Geçmişi',
  },

  moderation: {
    reportUser: 'Kullanıcıyı Şikayet Et',
    reportReason: 'Şikayet Nedeni',
    reportDetails: 'Detaylar (isteğe bağlı)',
    reportDetailsPlaceholder: 'Şikayetinizi açıklayın...',
    reportSubmit: 'Şikayeti Gönder',
    reportSuccess: 'Şikayetiniz alındı. İnceleme ekibimiz en kısa sürede değerlendirecektir.',
    blockUser: 'Kullanıcıyı Engelle',
    blockConfirm: '{name} engellenecek. Bu kullanıcı sizi göremeyecek ve sizinle iletişim kuramayacak.',
    blockSuccess: 'Kullanıcı engellendi',
    unblockUser: 'Engeli Kaldır',
    unblockConfirm: '{name} engeli kaldırılacak. Emin misiniz?',
    unblockSuccess: 'Engel kaldırıldı',
    reasonSpam: 'Spam',
    reasonInappropriatePhotos: 'Uygunsuz Fotoğraflar',
    reasonHarassment: 'Taciz',
    reasonUnderage: 'Yaş Sınırı İhlali',
    reasonFakeProfile: 'Sahte Profil',
    reasonOther: 'Diğer',
  },

  places: {
    title: 'Mekanlar',
    checkIn: 'Check-in Yap',
    checkInSuccess: 'Check-in yapıldı!',
    sharedPlaces: 'Ortak Mekanlar',
    sharedPlacesSubtitle: 'İkinizin de gittiği mekanlar',
    noSharedPlaces: 'Henüz ortak mekanınız yok',
    addMemory: 'Anı Ekle',
    addMemoryPlaceholder: 'Bu mekanla ilgili bir anınızı paylaşın...',
    memoryAdded: 'Anı eklendi!',
    memories: 'Anılar',
    visitCount: '{count} kez ziyaret edildi',
    lastVisit: 'Son ziyaret: {date}',
    nearbyPlaces: 'Yakındaki Mekanlar',
  },

  relationship: {
    title: 'İlişki',
    activate: 'İlişkiyi Aktive Et',
    activateSubtitle: '{name} ile ilişkinizi resmileştirin',
    activateConfirm: 'Her iki tarafın da onaylaması gerekmektedir.',
    deactivate: 'İlişkiyi Sonlandır',
    deactivateConfirm: 'İlişkiyi sonlandırmak istediğinize emin misiniz? Bu işlem geri alınamaz.',
    status: 'İlişki Durumu',
    active: 'Aktif',
    inactive: 'Aktif Değil',
    since: '{date} tarihinden beri birlikte',
    visibility: 'Profilde Görünürlük',
    visibilityOn: 'İlişki durumunuz profilinizde görünür',
    visibilityOff: 'İlişki durumunuz gizli',
    partnerPending: 'Partnerinizin onayı bekleniyor',
  },

  couplesClub: {
    title: 'Çiftler Kulübü',
    subtitle: 'İlişkinizi güçlendirin',
    exclusiveContent: 'Özel İçerikler',
    activities: 'Aktiviteler',
    dateIdeas: 'Randevu Fikirleri',
    challenges: 'Çift Görevleri',
    milestones: 'Kilometre Taşları',
    anniversary: 'Yıldönümü',
    daysTogather: '{count} gündür birlikte',
    comingSoon: 'Yakında',
  },

  notifications: {
    title: 'Bildirimler',
    noNotifications: 'Bildirim yok',
    noNotificationsSubtitle: 'Yeni gelişmelerden haberdar olacaksınız',
    markAllRead: 'Tümünü Okundu İşaretle',
    newMatch: '{name} ile eşleştiniz!',
    newMessage: '{name}: {preview}',
    harmonyInvite: '{name} sizi Harmony\'ye davet ediyor',
    badgeEarned: 'Yeni rozet kazandınız: {badge}',
    systemUpdate: 'Sistem güncellemesi',
    permissionRequired: 'Bildirim İzni',
    permissionMessage: 'Eşleşme ve mesajlardan haberdar olmak için bildirimlere izin verin',
    enableNotifications: 'Bildirimleri Etkinleştir',
  },

  errors: {
    generic: 'Bir hata oluştu. Lütfen tekrar deneyin.',
    network: 'İnternet bağlantınızı kontrol edin.',
    timeout: 'İstek zaman aşımına uğradı. Lütfen tekrar deneyin.',
    unauthorized: 'Oturumunuz sona erdi. Lütfen tekrar giriş yapın.',
    forbidden: 'Bu işlem için yetkiniz yok.',
    notFound: 'Aradığınız içerik bulunamadı.',
    serverError: 'Sunucu hatası. Lütfen daha sonra tekrar deneyin.',
    invalidPhone: 'Geçersiz telefon numarası.',
    invalidCode: 'Geçersiz doğrulama kodu.',
    codeExpired: 'Doğrulama kodunun süresi doldu.',
    photoTooLarge: 'Fotoğraf boyutu çok büyük. Maksimum 10 MB.',
    unsupportedFormat: 'Desteklenmeyen dosya formatı.',
    bioTooShort: 'Hakkında metni en az 10 karakter olmalıdır.',
    bioTooLong: 'Hakkında metni en fazla 500 karakter olabilir.',
    minPhotosRequired: 'En az 2 fotoğraf eklemeniz gerekmektedir.',
    maxPhotosReached: 'En fazla 6 fotoğraf ekleyebilirsiniz.',
    dailyLimitReached: 'Günlük beğeni limitinize ulaştınız.',
    insufficientGold: 'Yeterli Gold bakiyeniz yok.',
    alreadyMatched: 'Bu kullanıcıyla zaten eşleşmişsiniz.',
    matchNotFound: 'Eşleşme bulunamadı.',
    sessionExpired: 'Harmony oturumu sona erdi.',
    sessionFull: 'Harmony oturumu dolu.',
    alreadyReported: 'Bu kullanıcıyı zaten şikayet ettiniz.',
    alreadyBlocked: 'Bu kullanıcı zaten engellenmiş.',
    cannotBlockSelf: 'Kendinizi engelleyemezsiniz.',
    profileIncomplete: 'Lütfen önce profilinizi tamamlayın.',
    subscriptionRequired: 'Bu özellik için abonelik gereklidir.',
    upgradeRequired: 'Bu özellik için paketinizi yükseltmeniz gerekiyor.',
  },
} as const;
