// LUMA V1 — Turkish Strings (User-Facing)
// All user-facing strings in Turkish as per project language rules.

export const TR = {
  common: {
    appName: 'LUMA',
    loading: 'Yükleniyor...',
    save: 'Kaydet',
    cancel: 'İptal',
    confirm: 'Onayla',
    delete: 'Sil',
    edit: 'Düzenle',
    done: 'Tamam',
    next: 'İleri',
    back: 'Geri',
    close: 'Kapat',
    search: 'Ara',
    retry: 'Tekrar Dene',
    yes: 'Evet',
    no: 'Hayır',
    ok: 'Tamam',
    send: 'Gönder',
    share: 'Paylaş',
    apply: 'Uygula',
    reset: 'Sıfırla',
    seeAll: 'Tümünü Gör',
    noResults: 'Sonuç bulunamadı',
    optional: 'İsteğe bağlı',
    required: 'Zorunlu',
    online: 'Çevrimiçi',
    offline: 'Çevrimdışı',
    today: 'Bugün',
    yesterday: 'Dün',
    justNow: 'Az önce',
    minutesAgo: '{count} dakika önce',
    hoursAgo: '{count} saat önce',
    daysAgo: '{count} gün önce',
  },

  auth: {
    welcome: 'LUMA\'ya Hoş Geldin',
    welcomeSubtitle: 'Gerçek bağlantılar burada başlar',
    phoneNumber: 'Telefon Numarası',
    phoneNumberPlaceholder: '+90 5XX XXX XX XX',
    sendCode: 'Kod Gönder',
    verifyCode: 'Kodu Doğrula',
    enterCode: 'Doğrulama kodunu girin',
    codeSent: 'Kod gönderildi',
    codeExpiry: 'Kod {seconds} saniye içinde geçersiz olacak',
    resendCode: 'Kodu Tekrar Gönder',
    selfieVerification: 'Selfie Doğrulama',
    selfieInstructions: 'Yüzünüzü çerçevenin içine yerleştirin ve fotoğraf çekin',
    takeSelfie: 'Selfie Çek',
    retakeSelfie: 'Tekrar Çek',
    verifying: 'Doğrulanıyor...',
    verificationSuccess: 'Doğrulama başarılı!',
    verificationFailed: 'Doğrulama başarısız. Lütfen tekrar deneyin.',
    logout: 'Çıkış Yap',
    logoutConfirm: 'Çıkış yapmak istediğinize emin misiniz?',
    deleteAccount: 'Hesabı Sil',
    deleteAccountConfirm: 'Hesabınız kalıcı olarak silinecektir. Bu işlem geri alınamaz.',
    termsOfService: 'Kullanım Koşulları',
    privacyPolicy: 'Gizlilik Politikası',
    agreeTerms: 'Devam ederek Kullanım Koşullarını ve Gizlilik Politikasını kabul ediyorsunuz',
  },

  onboarding: {
    title: 'Profilini Oluştur',
    stepName: 'İsim',
    stepBirthDate: 'Doğum Tarihi',
    stepGender: 'Cinsiyet',
    stepPhotos: 'Fotoğraflar',
    stepBio: 'Hakkında',
    stepIntention: 'Niyet',
    stepQuestions: 'Sorular',
    firstName: 'Adınız',
    firstNamePlaceholder: 'Adınızı girin',
    birthDate: 'Doğum Tarihi',
    birthDatePlaceholder: 'GG / AA / YYYY',
    gender: 'Cinsiyet',
    genderMale: 'Erkek',
    genderFemale: 'Kadın',
    genderOther: 'Diğer',
    photos: 'Fotoğraflar',
    photosSubtitle: 'En az 2, en fazla 9 fotoğraf ekleyin',
    addPhoto: 'Fotoğraf Ekle',
    bio: 'Hakkında',
    bioPlaceholder: 'Kendinizden bahsedin... (en az 10 karakter)',
    bioCharCount: '{count}/500',
    intention: 'Hedefin Ne?',
    intentionEvlenmek: 'Evlenmek',
    intentionIliski: 'Bir ilişki bulmak',
    intentionSohbet: 'Sohbet etmek ve arkadaşlarla tanışmak',
    intentionKultur: 'Diğer kültürleri öğrenmek',
    intentionDunyaGezme: 'Dünyayı gezmek',
    questionsTitle: 'Uyumluluk Soruları',
    questionsSubtitle: '20 temel soruyu yanıtlayarak eşleşme puanınızı artırın',
    questionProgress: 'Soru {current}/{total}',
    completeProfile: 'Profili Tamamla',
    profileComplete: 'Profil oluşturuldu!',
    letsStart: 'Keşfetmeye Başla',
  },

  discovery: {
    title: 'Keşfet',
    noMoreProfiles: 'Şu an için gösterecek profil kalmadı',
    checkBackLater: 'Daha sonra tekrar kontrol edin',
    like: 'Beğen',
    pass: 'Geç',
    superLike: 'Süper Beğeni',
    undoSwipe: 'Geri Al',
    dailyLimitReached: 'Günlük beğeni limitine ulaştınız',
    upgradeForMore: 'Daha fazla beğeni için paketinizi yükseltin',
    filters: 'Filtreler',
    filterAge: 'Yaş Aralığı',
    filterDistance: 'Mesafe',
    filterGender: 'Cinsiyet Tercihi',
    filterIntention: 'Niyet Etiketi',
    filterGenderAll: 'Herkesi Göster',
    filterGenderMale: 'Erkek',
    filterGenderFemale: 'Kadın',
    distance: '{km} km',
    age: '{age} yaşında',
    compatibilityScore: '%{score} Uyumlu',
  },

  matches: {
    title: 'Eşleşmeler',
    noMatches: 'Henüz eşleşmeniz yok',
    noMatchesSubtitle: 'Keşfet sayfasından beğenmeye başlayın',
    newMatch: 'Yeni Eşleşme!',
    newMatchSubtitle: '{name} ile eşleştiniz!',
    sendMessage: 'Mesaj Gönder',
    startChat: 'Mesaj Gönder',
    matchDate: '{date} tarihinde eşleşildi',
    normalMatch: 'Eşleşme',
    superMatch: 'Süper Uyum!',
    superMatchSubtitle: '%{score} üstü uyumluluk!',
    unmatch: 'Eşleşmeyi Kaldır',
    unmatchConfirm: '{name} ile eşleşmeniz kalıcı olarak kaldırılacak. Emin misiniz?',
  },

  canli: {
    title: 'Canlı',
    subtitle: 'Uyumuna göre biriyle anında tanış',
    connect: 'Bağlan',
    searching: 'Uyumlu biri aranıyor...',
    connecting: 'Bağlanıyor...',
    connected: 'Bağlandı!',
    sessionEnded: 'Görüşme sona erdi',
    noOneAvailable: 'Şu an uygun biri bulunamadı',
    tryAgain: 'Tekrar Dene',
    jetonCost: '{amount} jeton',
    jetonRequired: 'Canlı görüşme için {amount} jeton gerekli',
    dailyLimitReached: 'Günlük canlı görüşme limitine ulaştın',
    upgradeForMore: 'Daha fazla görüşme için paketini yükselt',
    endActions: {
      takipEt: 'Takip Et',
      begen: 'Beğen',
      sonraki: 'Sonraki',
    },
    matchMade: '{name} ile eşleştin!',
    friendMade: '{name} ile arkadaş oldun!',
    compatibilityScore: '%{score} uyumlu',
  },

  chat: {
    title: 'Mesajlar',
    noConversations: 'Henüz mesajınız yok',
    noConversationsSubtitle: 'Eşleşmelerinize mesaj göndererek sohbet başlatın',
    typeMessage: 'Mesaj yazın...',
    sendPhoto: 'Fotoğraf Gönder',
    messageRead: 'Okundu',
    messageDelivered: 'İletildi',
    messageSent: 'Gönderildi',
    typing: 'yazıyor...',
    online: 'Çevrimiçi',
    lastSeen: 'Son görülme: {time}',
    deletedMessage: 'Bu mesaj silindi',
    systemMessage: 'Sistem Mesajı',
    imageMessage: 'Fotoğraf',
    unreadMessages: '{count} okunmamış mesaj',
  },

  profile: {
    title: 'Profil',
    editProfile: 'Profili Düzenle',
    viewProfile: 'Profili Görüntüle',
    myPhotos: 'Fotoğraflarım',
    myBio: 'Hakkımda',
    myIntention: 'Niyetim',
    myBadges: 'Rozetlerim',
    myAnswers: 'Yanıtlarım',
    compatibility: 'Uyumluluk',
    verificationStatus: 'Doğrulama Durumu',
    verified: 'Doğrulanmış',
    notVerified: 'Doğrulanmamış',
    completeVerification: 'Doğrulamayı Tamamla',
    jetonBalance: 'Jeton Bakiyesi',
    currentPackage: 'Mevcut Paket',
    memberSince: '{date} tarihinden beri üye',
    editBio: 'Hakkımda Düzenle',
    editPhotos: 'Fotoğrafları Düzenle',
    changeIntention: 'Niyeti Değiştir',
    profileViews: 'Profil Görüntülenme',
    swipeStats: 'Beğeni İstatistikleri',
  },

  settings: {
    title: 'Ayarlar',
    account: 'Hesap',
    notifications: 'Bildirimler',
    privacy: 'Gizlilik',
    language: 'Dil',
    darkMode: 'Karanlık Mod',
    about: 'Hakkında',
    help: 'Yardım',
    support: 'Destek',
    rateApp: 'Uygulamayı Değerlendir',
    version: 'Versiyon {version}',
    notificationMatches: 'Eşleşme Bildirimleri',
    notificationMessages: 'Mesaj Bildirimleri',
    notificationCanli: 'Canlı Bildirimleri',
    notificationBadges: 'Rozet Bildirimleri',
    notificationSystem: 'Sistem Bildirimleri',
    privacyShowOnline: 'Çevrimiçi Durumunu Göster',
    privacyShowDistance: 'Mesafeyi Göster',
    privacyShowLastSeen: 'Son Görülmeyi Göster',
    blockedUsers: 'Engellenen Kullanıcılar',
    deleteAccount: 'Hesabı Sil',
  },

  badges: {
    title: 'Rozetler',
    myBadges: 'Rozetlerim',
    allBadges: 'Tüm Rozetler',
    earned: 'Kazanıldı',
    locked: 'Kilitli',
    earnedDate: '{date} tarihinde kazanıldı',
    firstSpark: 'İlk Kıvılcım',
    firstSparkDesc: 'İlk eşleşmenizi yapın',
    chatMaster: 'Sohbet Ustası',
    chatMasterDesc: '100 mesaj gönderin',
    questionExplorer: 'Merak Uzmanı',
    questionExplorerDesc: 'Tüm uyumluluk sorularını yanıtlayın',
    soulMate: 'Ruh İkizi',
    soulMateDesc: '%90 üstü uyumluluk elde edin',
    verifiedStar: 'Doğrulanmış Yıldız',
    verifiedStarDesc: 'Selfie doğrulamasını tamamlayın',
    coupleGoal: 'Çift Hedefi',
    coupleGoalDesc: 'Bir ilişkiyi aktive edin',
    explorer: 'Kaşif',
    explorerDesc: '50 profil keşfedin',
    premiumMember: 'Premium Üye',
    premiumMemberDesc: 'Premium veya Supreme pakete sahip ol',
    newBadge: 'Yeni Rozet Kazandınız!',
    jetonReward: '+{amount} jeton ödül!',
  },

  packages: {
    title: 'Üyelik',
    currentPlan: 'Mevcut Paket',
    free: 'Ücretsiz',
    freeDesc: 'Temel özellikler',
    premium: 'Premium',
    premiumDesc: 'Tam erişim, makul limitlerle',
    premiumPrice: '499₺/ay',
    supreme: 'Supreme',
    supremeDesc: 'Sınırsız + özel ayrıcalıklar',
    supremePrice: '1.199₺/ay',
    supremeBadge: 'En Popüler',
    subscribe: 'Abone Ol',
    upgrade: 'Yükselt',
    cancelSubscription: 'Aboneliği İptal Et',
    cancelConfirm: 'Aboneliğiniz dönem sonuna kadar aktif kalacaktır. İptal etmek istediğinize emin misiniz?',
    monthlyPrice: '₺{price}/ay',
    features: 'Özellikler',
    unlimitedLikes: 'Sınırsız beğeni',
    monthlyJeton: 'Aylık {count} jeton',
    adFree: 'Reklamsız deneyim',
    seeWhoLikedYou: 'Seni beğenenleri gör',
    readReceipts: 'Okundu bilgisi',
    profileBoost: 'Profili öne çıkar',
    undoSwipe: 'Beğeniyi geri al',
    priorityInFeed: 'Keşfette öncelik',
    advancedFilters: 'Gelişmiş filtreler',
    dailyMatch: 'Günün eşleşmesi',
    unlimitedCanli: 'Sınırsız canlı görüşme',
    jetonTitle: 'Jeton',
    jetonBalance: 'Bakiye: {amount} jeton',
    buyJeton: 'Jeton Satın Al',
    jetonPack: '{amount} Jeton',
    jetonPackPrice: '₺{price}',
    transactionHistory: 'İşlem Geçmişi',
  },

  moderation: {
    reportUser: 'Kullanıcıyı Şikayet Et',
    reportReason: 'Şikayet Nedeni',
    reportDetails: 'Detaylar (isteğe bağlı)',
    reportDetailsPlaceholder: 'Şikayetinizi açıklayın...',
    reportSubmit: 'Şikayeti Gönder',
    reportSuccess: 'Şikayetiniz alındı. İnceleme ekibimiz en kısa sürede değerlendirecektir.',
    blockUser: 'Kullanıcıyı Engelle',
    blockConfirm: '{name} engellenecek. Bu kullanıcı sizi göremeyecek ve sizinle iletişim kuramayacak.',
    blockSuccess: 'Kullanıcı engellendi',
    unblockUser: 'Engeli Kaldır',
    unblockConfirm: '{name} engeli kaldırılacak. Emin misiniz?',
    unblockSuccess: 'Engel kaldırıldı',
    reasonSpam: 'Spam',
    reasonInappropriatePhotos: 'Uygunsuz Fotoğraflar',
    reasonHarassment: 'Taciz',
    reasonUnderage: 'Yaş Sınırı İhlali',
    reasonFakeProfile: 'Sahte Profil',
    reasonOther: 'Diğer',
  },

  places: {
    title: 'Mekanlar',
    checkIn: 'Check-in Yap',
    checkInSuccess: 'Check-in yapıldı!',
    sharedPlaces: 'Ortak Mekanlar',
    sharedPlacesSubtitle: 'İkinizin de gittiği mekanlar',
    noSharedPlaces: 'Henüz ortak mekanınız yok',
    addMemory: 'Anı Ekle',
    addMemoryPlaceholder: 'Bu mekanla ilgili bir anınızı paylaşın...',
    memoryAdded: 'Anı eklendi!',
    memories: 'Anılar',
    visitCount: '{count} kez ziyaret edildi',
    lastVisit: 'Son ziyaret: {date}',
    nearbyPlaces: 'Yakındaki Mekanlar',
  },

  feed: {
    title: 'Akış',
    popular: 'Popüler',
    following: 'Takip',
    createPost: 'Gönderini paylaş...',
    postTypes: {
      photo: 'Fotoğraf',
      video: 'Video',
      text: 'Yazı',
    },
    like: 'Beğen',
    comment: 'Yorum',
    follow: 'Takip Et',
    unfollow: 'Takibi Bırak',
    visitProfile: 'Profili ziyaret et',
    noPostsPopular: 'Henüz gönderi yok',
    noPostsFollowing: 'Takip ettiğin kişilerin gönderilerini burada göreceksin',
    stories: 'Hikayeler',
    addStory: 'Hikaye Ekle',
    storyExpired: 'Bu hikayenin süresi doldu',
    dailyStoryLimit: 'Günlük hikaye limitine ulaştın',
  },

  follows: {
    followers: 'Takipçiler',
    following: 'Takip Edilenler',
    follow: 'Takip Et',
    unfollow: 'Takibi Bırak',
    mutualFollow: 'Arkadaş oldunuz!',
    noFollowers: 'Henüz takipçin yok',
    noFollowing: 'Henüz kimseyi takip etmiyorsun',
  },

  notifications: {
    title: 'Bildirimler',
    noNotifications: 'Bildirim yok',
    noNotificationsSubtitle: 'Yeni gelişmelerden haberdar olacaksınız',
    markAllRead: 'Tümünü Okundu İşaretle',
    newMatch: '{name} ile eşleştiniz!',
    newMessage: '{name}: {preview}',
    superLikeReceived: '{name} seni süper beğendi!',
    newFollower: '{name} seni takip etmeye başladı',
    badgeEarned: 'Yeni rozet kazandınız: {badge}',
    systemUpdate: 'Sistem güncellemesi',
    permissionRequired: 'Bildirim İzni',
    permissionMessage: 'Eşleşme ve mesajlardan haberdar olmak için bildirimlere izin verin',
    enableNotifications: 'Bildirimleri Etkinleştir',
  },

  errors: {
    generic: 'Bir hata oluştu. Lütfen tekrar deneyin.',
    network: 'İnternet bağlantınızı kontrol edin.',
    timeout: 'İstek zaman aşımına uğradı. Lütfen tekrar deneyin.',
    unauthorized: 'Oturumunuz sona erdi. Lütfen tekrar giriş yapın.',
    forbidden: 'Bu işlem için yetkiniz yok.',
    notFound: 'Aradığınız içerik bulunamadı.',
    serverError: 'Sunucu hatası. Lütfen daha sonra tekrar deneyin.',
    invalidPhone: 'Geçersiz telefon numarası.',
    invalidCode: 'Geçersiz doğrulama kodu.',
    codeExpired: 'Doğrulama kodunun süresi doldu.',
    photoTooLarge: 'Fotoğraf boyutu çok büyük. Maksimum 10 MB.',
    unsupportedFormat: 'Desteklenmeyen dosya formatı.',
    bioTooShort: 'Hakkında metni en az 10 karakter olmalıdır.',
    bioTooLong: 'Hakkında metni en fazla 500 karakter olabilir.',
    minPhotosRequired: 'En az 2 fotoğraf eklemeniz gerekmektedir.',
    maxPhotosReached: 'En fazla 9 fotoğraf ekleyebilirsiniz.',
    dailyLimitReached: 'Günlük beğeni limitinize ulaştınız.',
    insufficientJeton: 'Yeterli jeton bakiyen yok.',
    alreadyMatched: 'Bu kullanıcıyla zaten eşleşmişsiniz.',
    matchNotFound: 'Eşleşme bulunamadı.',
    canliNoMatch: 'Uygun biri bulunamadı, tekrar dene.',
    canliSessionFailed: 'Bağlantı kurulamadı.',
    alreadyReported: 'Bu kullanıcıyı zaten şikayet ettiniz.',
    alreadyBlocked: 'Bu kullanıcı zaten engellenmiş.',
    cannotBlockSelf: 'Kendinizi engelleyemezsiniz.',
    profileIncomplete: 'Lütfen önce profilinizi tamamlayın.',
    subscriptionRequired: 'Bu özellik için abonelik gereklidir.',
    upgradeRequired: 'Bu özellik için paketinizi yükseltmeniz gerekiyor.',
  },
} as const;
