export declare const TR: {
    readonly common: {
        readonly appName: "LUMA";
        readonly loading: "Yükleniyor...";
        readonly save: "Kaydet";
        readonly cancel: "İptal";
        readonly confirm: "Onayla";
        readonly delete: "Sil";
        readonly edit: "Düzenle";
        readonly done: "Tamam";
        readonly next: "İleri";
        readonly back: "Geri";
        readonly close: "Kapat";
        readonly search: "Ara";
        readonly retry: "Tekrar Dene";
        readonly yes: "Evet";
        readonly no: "Hayır";
        readonly ok: "Tamam";
        readonly send: "Gönder";
        readonly share: "Paylaş";
        readonly apply: "Uygula";
        readonly reset: "Sıfırla";
        readonly seeAll: "Tümünü Gör";
        readonly noResults: "Sonuç bulunamadı";
        readonly optional: "İsteğe bağlı";
        readonly required: "Zorunlu";
        readonly online: "Çevrimiçi";
        readonly offline: "Çevrimdışı";
        readonly today: "Bugün";
        readonly yesterday: "Dün";
        readonly justNow: "Az önce";
        readonly minutesAgo: "{count} dakika önce";
        readonly hoursAgo: "{count} saat önce";
        readonly daysAgo: "{count} gün önce";
    };
    readonly auth: {
        readonly welcome: "LUMA'ya Hoş Geldin";
        readonly welcomeSubtitle: "Gerçek bağlantılar burada başlar";
        readonly phoneNumber: "Telefon Numarası";
        readonly phoneNumberPlaceholder: "+90 5XX XXX XX XX";
        readonly sendCode: "Kod Gönder";
        readonly verifyCode: "Kodu Doğrula";
        readonly enterCode: "Doğrulama kodunu girin";
        readonly codeSent: "Kod gönderildi";
        readonly codeExpiry: "Kod {seconds} saniye içinde geçersiz olacak";
        readonly resendCode: "Kodu Tekrar Gönder";
        readonly selfieVerification: "Selfie Doğrulama";
        readonly selfieInstructions: "Yüzünüzü çerçevenin içine yerleştirin ve fotoğraf çekin";
        readonly takeSelfie: "Selfie Çek";
        readonly retakeSelfie: "Tekrar Çek";
        readonly verifying: "Doğrulanıyor...";
        readonly verificationSuccess: "Doğrulama başarılı!";
        readonly verificationFailed: "Doğrulama başarısız. Lütfen tekrar deneyin.";
        readonly logout: "Çıkış Yap";
        readonly logoutConfirm: "Çıkış yapmak istediğinize emin misiniz?";
        readonly deleteAccount: "Hesabı Sil";
        readonly deleteAccountConfirm: "Hesabınız kalıcı olarak silinecektir. Bu işlem geri alınamaz.";
        readonly termsOfService: "Kullanım Koşulları";
        readonly privacyPolicy: "Gizlilik Politikası";
        readonly agreeTerms: "Devam ederek Kullanım Koşullarını ve Gizlilik Politikasını kabul ediyorsunuz";
    };
    readonly onboarding: {
        readonly title: "Profilini Oluştur";
        readonly stepName: "İsim";
        readonly stepBirthDate: "Doğum Tarihi";
        readonly stepGender: "Cinsiyet";
        readonly stepPhotos: "Fotoğraflar";
        readonly stepBio: "Hakkında";
        readonly stepIntention: "Niyet";
        readonly stepQuestions: "Sorular";
        readonly firstName: "Adınız";
        readonly firstNamePlaceholder: "Adınızı girin";
        readonly birthDate: "Doğum Tarihi";
        readonly birthDatePlaceholder: "GG / AA / YYYY";
        readonly gender: "Cinsiyet";
        readonly genderMale: "Erkek";
        readonly genderFemale: "Kadın";
        readonly genderOther: "Diğer";
        readonly photos: "Fotoğraflar";
        readonly photosSubtitle: "En az 2, en fazla 6 fotoğraf ekleyin";
        readonly addPhoto: "Fotoğraf Ekle";
        readonly bio: "Hakkında";
        readonly bioPlaceholder: "Kendinizden bahsedin... (en az 10 karakter)";
        readonly bioCharCount: "{count}/500";
        readonly intention: "Ne Arıyorsunuz?";
        readonly intentionSerious: "Ciddi İlişki";
        readonly intentionExploring: "Keşfediyorum";
        readonly intentionNotSure: "Emin Değilim";
        readonly questionsTitle: "Uyumluluk Soruları";
        readonly questionsSubtitle: "20 temel soruyu yanıtlayarak eşleşme puanınızı artırın";
        readonly questionProgress: "Soru {current}/{total}";
        readonly completeProfile: "Profili Tamamla";
        readonly profileComplete: "Profil oluşturuldu!";
        readonly letsStart: "Keşfetmeye Başla";
    };
    readonly discovery: {
        readonly title: "Keşfet";
        readonly noMoreProfiles: "Şu an için gösterecek profil kalmadı";
        readonly checkBackLater: "Daha sonra tekrar kontrol edin";
        readonly like: "Beğen";
        readonly pass: "Geç";
        readonly superLike: "Süper Beğeni";
        readonly undoSwipe: "Geri Al";
        readonly dailyLimitReached: "Günlük beğeni limitine ulaştınız";
        readonly upgradeForMore: "Daha fazla beğeni için paketinizi yükseltin";
        readonly filters: "Filtreler";
        readonly filterAge: "Yaş Aralığı";
        readonly filterDistance: "Mesafe";
        readonly filterGender: "Cinsiyet Tercihi";
        readonly filterIntention: "Niyet Etiketi";
        readonly filterGenderAll: "Herkesi Göster";
        readonly filterGenderMale: "Erkek";
        readonly filterGenderFemale: "Kadın";
        readonly distance: "{km} km";
        readonly age: "{age} yaşında";
        readonly compatibilityScore: "%{score} Uyumlu";
    };
    readonly matches: {
        readonly title: "Eşleşmeler";
        readonly noMatches: "Henüz eşleşmeniz yok";
        readonly noMatchesSubtitle: "Keşfet sayfasından beğenmeye başlayın";
        readonly newMatch: "Yeni Eşleşme!";
        readonly newMatchSubtitle: "{name} ile eşleştiniz!";
        readonly sendMessage: "Mesaj Gönder";
        readonly matchDate: "{date} tarihinde eşleşildi";
        readonly normalMatch: "Eşleşme";
        readonly superMatch: "Süper Uyum!";
        readonly superMatchSubtitle: "%{score} üstü uyumluluk!";
        readonly unmatch: "Eşleşmeyi Kaldır";
        readonly unmatchConfirm: "{name} ile eşleşmeniz kalıcı olarak kaldırılacak. Emin misiniz?";
    };
    readonly chat: {
        readonly title: "Mesajlar";
        readonly noConversations: "Henüz mesajınız yok";
        readonly noConversationsSubtitle: "Eşleşmelerinize mesaj göndererek sohbet başlatın";
        readonly typeMessage: "Mesaj yazın...";
        readonly sendPhoto: "Fotoğraf Gönder";
        readonly messageRead: "Okundu";
        readonly messageDelivered: "İletildi";
        readonly messageSent: "Gönderildi";
        readonly typing: "yazıyor...";
        readonly online: "Çevrimiçi";
        readonly lastSeen: "Son görülme: {time}";
        readonly deletedMessage: "Bu mesaj silindi";
        readonly systemMessage: "Sistem Mesajı";
        readonly imageMessage: "Fotoğraf";
        readonly unreadMessages: "{count} okunmamış mesaj";
        readonly voiceCall: "Sesli Arama";
        readonly videoCall: "Görüntülü Arama";
        readonly callCost: "{cost} Gold ile {type} başlat";
        readonly callIncoming: "{name} sizi arıyor";
        readonly callEnded: "Arama sona erdi";
        readonly callRejected: "Arama reddedildi";
        readonly callBusy: "Karşı taraf meşgul";
        readonly callOffline: "Karşı taraf çevrimdışı";
        readonly callRequiresPackage: "Arama yapabilmek için paket sahibi olmanız gerekiyor";
        readonly callInsufficientGold: "Yetersiz Gold bakiyesi";
        readonly voiceCallCost: "Sesli arama: 25 Gold";
        readonly videoCallCost: "Görüntülü arama: 50 Gold";
    };
    readonly profile: {
        readonly title: "Profil";
        readonly editProfile: "Profili Düzenle";
        readonly viewProfile: "Profili Görüntüle";
        readonly myPhotos: "Fotoğraflarım";
        readonly myBio: "Hakkımda";
        readonly myIntention: "Niyetim";
        readonly myBadges: "Rozetlerim";
        readonly myAnswers: "Yanıtlarım";
        readonly compatibility: "Uyumluluk";
        readonly verificationStatus: "Doğrulama Durumu";
        readonly verified: "Doğrulanmış";
        readonly notVerified: "Doğrulanmamış";
        readonly completeVerification: "Doğrulamayı Tamamla";
        readonly goldBalance: "Gold Bakiyesi";
        readonly currentPackage: "Mevcut Paket";
        readonly memberSince: "{date} tarihinden beri üye";
        readonly editBio: "Hakkımda Düzenle";
        readonly editPhotos: "Fotoğrafları Düzenle";
        readonly changeIntention: "Niyeti Değiştir";
        readonly profileViews: "Profil Görüntülenme";
        readonly swipeStats: "Beğeni İstatistikleri";
    };
    readonly settings: {
        readonly title: "Ayarlar";
        readonly account: "Hesap";
        readonly notifications: "Bildirimler";
        readonly privacy: "Gizlilik";
        readonly language: "Dil";
        readonly darkMode: "Karanlık Mod";
        readonly about: "Hakkında";
        readonly help: "Yardım";
        readonly support: "Destek";
        readonly rateApp: "Uygulamayı Değerlendir";
        readonly version: "Versiyon {version}";
        readonly notificationMatches: "Eşleşme Bildirimleri";
        readonly notificationMessages: "Mesaj Bildirimleri";
        readonly notificationBadges: "Rozet Bildirimleri";
        readonly notificationSystem: "Sistem Bildirimleri";
        readonly privacyShowOnline: "Çevrimiçi Durumunu Göster";
        readonly privacyShowDistance: "Mesafeyi Göster";
        readonly privacyShowLastSeen: "Son Görülmeyi Göster";
        readonly blockedUsers: "Engellenen Kullanıcılar";
        readonly deleteAccount: "Hesabı Sil";
    };
    readonly badges: {
        readonly title: "Rozetler";
        readonly myBadges: "Rozetlerim";
        readonly allBadges: "Tüm Rozetler";
        readonly earned: "Kazanıldı";
        readonly locked: "Kilitli";
        readonly earnedDate: "{date} tarihinde kazanıldı";
        readonly firstSpark: "İlk Kıvılcım";
        readonly firstSparkDesc: "İlk eşleşmenizi yapın";
        readonly chatMaster: "Sohbet Ustası";
        readonly chatMasterDesc: "100 mesaj gönderin";
        readonly questionExplorer: "Merak Uzmanı";
        readonly questionExplorerDesc: "Tüm uyumluluk sorularını yanıtlayın";
        readonly soulMate: "Ruh İkizi";
        readonly soulMateDesc: "%90 üstü uyumluluk elde edin";
        readonly verifiedStar: "Doğrulanmış Yıldız";
        readonly verifiedStarDesc: "Selfie doğrulamasını tamamlayın";
        readonly coupleGoal: "Çift Hedefi";
        readonly coupleGoalDesc: "Bir ilişkiyi aktive edin";
        readonly explorer: "Kaşif";
        readonly explorerDesc: "50 profil keşfedin";
        readonly deepMatch: "Derin Uyum";
        readonly deepMatchDesc: "Derin uyum seviyesine ulaşın";
        readonly newBadge: "Yeni Rozet Kazandınız!";
        readonly goldReward: "+{amount} Gold ödül!";
    };
    readonly packages: {
        readonly title: "Paketler";
        readonly currentPlan: "Mevcut Plan";
        readonly free: "Ücretsiz";
        readonly freeDesc: "Temel özelliklerle başlayın";
        readonly gold: "Gold";
        readonly goldDesc: "Premium sorulara erişim ve daha fazla beğeni";
        readonly pro: "Pro";
        readonly proDesc: "Tüm özelliklere tam erişim";
        readonly reserved: "Reserved";
        readonly reservedDesc: "En özel deneyim";
        readonly subscribe: "Abone Ol";
        readonly upgrade: "Yükselt";
        readonly downgrade: "Düşür";
        readonly cancelSubscription: "Aboneliği İptal Et";
        readonly cancelConfirm: "Aboneliğiniz dönem sonuna kadar aktif kalacaktır. İptal etmek istediğinize emin misiniz?";
        readonly monthlyPrice: "₺{price}/ay";
        readonly yearlyPrice: "₺{price}/yıl";
        readonly yearlyDiscount: "%{percent} indirim";
        readonly features: "Özellikler";
        readonly dailySwipes: "Günlük {count} beğeni";
        readonly unlimitedSwipes: "Sınırsız beğeni";
        readonly monthlyGold: "Aylık {count} Gold";
        readonly premiumQuestions: "Premium uyumluluk soruları";
        readonly seeWhoLikedYou: "Sizi beğenenleri görün";
        readonly readReceipts: "Okundu bilgisi";
        readonly profileBoost: "Profil öne çıkarma";
        readonly undoSwipe: "Beğeniyi geri alma";
        readonly priorityInFeed: "Keşfette öncelik";
        readonly goldTitle: "Gold";
        readonly goldBalance: "Bakiye: {amount} Gold";
        readonly buyGold: "Gold Satın Al";
        readonly goldPack: "{amount} Gold";
        readonly goldPackPrice: "₺{price}";
        readonly goldPackBonus: "+{bonus} bonus!";
        readonly transactionHistory: "İşlem Geçmişi";
    };
    readonly moderation: {
        readonly reportUser: "Kullanıcıyı Şikayet Et";
        readonly reportReason: "Şikayet Nedeni";
        readonly reportDetails: "Detaylar (isteğe bağlı)";
        readonly reportDetailsPlaceholder: "Şikayetinizi açıklayın...";
        readonly reportSubmit: "Şikayeti Gönder";
        readonly reportSuccess: "Şikayetiniz alındı. İnceleme ekibimiz en kısa sürede değerlendirecektir.";
        readonly blockUser: "Kullanıcıyı Engelle";
        readonly blockConfirm: "{name} engellenecek. Bu kullanıcı sizi göremeyecek ve sizinle iletişim kuramayacak.";
        readonly blockSuccess: "Kullanıcı engellendi";
        readonly unblockUser: "Engeli Kaldır";
        readonly unblockConfirm: "{name} engeli kaldırılacak. Emin misiniz?";
        readonly unblockSuccess: "Engel kaldırıldı";
        readonly reasonSpam: "Spam";
        readonly reasonInappropriatePhotos: "Uygunsuz Fotoğraflar";
        readonly reasonHarassment: "Taciz";
        readonly reasonUnderage: "Yaş Sınırı İhlali";
        readonly reasonFakeProfile: "Sahte Profil";
        readonly reasonOther: "Diğer";
    };
    readonly places: {
        readonly title: "Mekanlar";
        readonly checkIn: "Check-in Yap";
        readonly checkInSuccess: "Check-in yapıldı!";
        readonly sharedPlaces: "Ortak Mekanlar";
        readonly sharedPlacesSubtitle: "İkinizin de gittiği mekanlar";
        readonly noSharedPlaces: "Henüz ortak mekanınız yok";
        readonly addMemory: "Anı Ekle";
        readonly addMemoryPlaceholder: "Bu mekanla ilgili bir anınızı paylaşın...";
        readonly memoryAdded: "Anı eklendi!";
        readonly memories: "Anılar";
        readonly visitCount: "{count} kez ziyaret edildi";
        readonly lastVisit: "Son ziyaret: {date}";
        readonly nearbyPlaces: "Yakındaki Mekanlar";
    };
    readonly relationship: {
        readonly title: "İlişki";
        readonly activate: "İlişkiyi Aktive Et";
        readonly activateSubtitle: "{name} ile ilişkinizi resmileştirin";
        readonly activateConfirm: "Her iki tarafın da onaylaması gerekmektedir.";
        readonly deactivate: "İlişkiyi Sonlandır";
        readonly deactivateConfirm: "İlişkiyi sonlandırmak istediğinize emin misiniz? Bu işlem geri alınamaz.";
        readonly status: "İlişki Durumu";
        readonly active: "Aktif";
        readonly inactive: "Aktif Değil";
        readonly since: "{date} tarihinden beri birlikte";
        readonly visibility: "Profilde Görünürlük";
        readonly visibilityOn: "İlişki durumunuz profilinizde görünür";
        readonly visibilityOff: "İlişki durumunuz gizli";
        readonly partnerPending: "Partnerinizin onayı bekleniyor";
    };
    readonly couplesClub: {
        readonly title: "Çiftler Kulübü";
        readonly subtitle: "İlişkinizi güçlendirin";
        readonly exclusiveContent: "Özel İçerikler";
        readonly activities: "Aktiviteler";
        readonly dateIdeas: "Randevu Fikirleri";
        readonly challenges: "Çift Görevleri";
        readonly milestones: "Kilometre Taşları";
        readonly anniversary: "Yıldönümü";
        readonly daysTogather: "{count} gündür birlikte";
        readonly comingSoon: "Yakında";
    };
    readonly notifications: {
        readonly title: "Bildirimler";
        readonly noNotifications: "Bildirim yok";
        readonly noNotificationsSubtitle: "Yeni gelişmelerden haberdar olacaksınız";
        readonly markAllRead: "Tümünü Okundu İşaretle";
        readonly newMatch: "{name} ile eşleştiniz!";
        readonly newMessage: "{name}: {preview}";
        readonly badgeEarned: "Yeni rozet kazandınız: {badge}";
        readonly systemUpdate: "Sistem güncellemesi";
        readonly permissionRequired: "Bildirim İzni";
        readonly permissionMessage: "Eşleşme ve mesajlardan haberdar olmak için bildirimlere izin verin";
        readonly enableNotifications: "Bildirimleri Etkinleştir";
    };
    readonly errors: {
        readonly generic: "Bir hata oluştu. Lütfen tekrar deneyin.";
        readonly network: "İnternet bağlantınızı kontrol edin.";
        readonly timeout: "İstek zaman aşımına uğradı. Lütfen tekrar deneyin.";
        readonly unauthorized: "Oturumunuz sona erdi. Lütfen tekrar giriş yapın.";
        readonly forbidden: "Bu işlem için yetkiniz yok.";
        readonly notFound: "Aradığınız içerik bulunamadı.";
        readonly serverError: "Sunucu hatası. Lütfen daha sonra tekrar deneyin.";
        readonly invalidPhone: "Geçersiz telefon numarası.";
        readonly invalidCode: "Geçersiz doğrulama kodu.";
        readonly codeExpired: "Doğrulama kodunun süresi doldu.";
        readonly photoTooLarge: "Fotoğraf boyutu çok büyük. Maksimum 10 MB.";
        readonly unsupportedFormat: "Desteklenmeyen dosya formatı.";
        readonly bioTooShort: "Hakkında metni en az 10 karakter olmalıdır.";
        readonly bioTooLong: "Hakkında metni en fazla 500 karakter olabilir.";
        readonly minPhotosRequired: "En az 2 fotoğraf eklemeniz gerekmektedir.";
        readonly maxPhotosReached: "En fazla 6 fotoğraf ekleyebilirsiniz.";
        readonly dailyLimitReached: "Günlük beğeni limitinize ulaştınız.";
        readonly insufficientGold: "Yeterli Gold bakiyeniz yok.";
        readonly alreadyMatched: "Bu kullanıcıyla zaten eşleşmişsiniz.";
        readonly matchNotFound: "Eşleşme bulunamadı.";
        readonly alreadyReported: "Bu kullanıcıyı zaten şikayet ettiniz.";
        readonly alreadyBlocked: "Bu kullanıcı zaten engellenmiş.";
        readonly cannotBlockSelf: "Kendinizi engelleyemezsiniz.";
        readonly profileIncomplete: "Lütfen önce profilinizi tamamlayın.";
        readonly subscriptionRequired: "Bu özellik için abonelik gereklidir.";
        readonly upgradeRequired: "Bu özellik için paketinizi yükseltmeniz gerekiyor.";
    };
};
//# sourceMappingURL=strings.d.ts.map